"""user ignored tables

Revision ID: ad2786ea98a0
Revises: 3fff3f6745bc
Create Date: 2025-08-19 14:14:30.339722

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

import models

# revision identifiers, used by Alembic.
revision = "ad2786ea98a0"
down_revision = "3fff3f6745bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ignored_artists",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("artist_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ts", models.types.UtcAwareDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_id"),
    )
    op.create_table(
        "ignored_tracks",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("track_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ts", models.types.UtcAwareDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "track_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ignored_tracks")
    op.drop_table("ignored_artists")
    # ### end Alembic commands ###
